server:
  port: 8203

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-product?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

aliyun:
  endpoint: oss-cn-guangzhou.aliyuncs.com
  keyid: LTAI5t6LTZEVmzxL6mJbxdrT
  keysecret: dnlFxOZndE2F5lLGTNy3VqS2IVoyoG
  bucketname: ssyx-hermit